/**
 * pbc-block-builder — public type contract.
 *
 * Generalizes FlowStudio v2's 23-block detail-page system (6 categories,
 * A1–F3) into a reusable PBC for landing pages, detail pages, SNS cards,
 * and business documents.
 *
 * Spec: docs/specs/meta-platform/pbc-block-builder.md §3.1
 *
 * WI-501 ships ONLY the type surface so dependent PBCs and apps can declare
 * their dependency against the contract. Concrete block definitions arrive
 * in WI-502; renderers in WI-503..WI-506; AI copy pipeline in WI-507;
 * presets in WI-508; FlowStudio v2 migration in WI-509.
 *
 * The category short names (`A`..`F`) are the load-bearing identifiers; the
 * human-readable names ("Hero" / "Feature" / etc.) are pinned in WI-502 once
 * the FlowStudio v2 `block-system-design.md` mapping is reconciled. Until
 * then this file only fixes the abstract category set.
 */

import type { ZodSchema } from "zod";

/**
 * Block category short names. The full set comes from FlowStudio v2's
 * 6-category taxonomy; WI-502 confirms the human-readable mapping. Keeping
 * the alphabetical short form as the canonical identifier means consumer
 * code does not break when the category labels (e.g. "Hero" vs "Above the
 * Fold") get renamed.
 */
export const BLOCK_CATEGORIES = ["A", "B", "C", "D", "E", "F"] as const;
export type BlockCategory = (typeof BLOCK_CATEGORIES)[number];

/**
 * Block id, e.g. `A1`, `B3`, `F2`. The numeric suffix is positional within
 * the category and matches FlowStudio v2's existing block ordering. The
 * 23-block enumeration ships in WI-502 alongside the per-block schema.
 */
export type BlockId = `${BlockCategory}${number}`;

/**
 * Render targets the PBC supports out of the box. WI-503..WI-506 ship the
 * adapters; new targets (e.g. PDF) can be added without changing this
 * type's structural contract — just extend the union and add an adapter.
 */
export const RENDER_OUTPUTS = ["html", "markdown", "react", "docx-element"] as const;
export type RenderOutput = (typeof RENDER_OUTPUTS)[number];

export const LOCALES = ["ko", "en"] as const;
export type Locale = (typeof LOCALES)[number];

/**
 * Design-token shape. Intentionally a free-form record per category so
 * `DESIGN.md` consumers can pass tokens in whatever shape their generator
 * produces. The future `core-design-md` PBC will narrow this.
 */
export interface DesignTokens {
  colors: Record<string, string>;
  typography: Record<string, string>;
  spacing: Record<string, string>;
  /** Free-form bag for tokens not captured by the three buckets above. */
  extras?: Record<string, unknown>;
}

/**
 * Asset reference produced alongside rendered content (e.g. images
 * generated by the optional image-engine, fonts a renderer needs to embed).
 * Apps decide how to materialize these (CDN upload, base64 inline, etc.).
 */
export interface RenderAsset {
  type: "image" | "font" | "video";
  src: string;
  /** Optional MIME type — useful for adapter-side content sniffing. */
  mimeType?: string;
}

/**
 * Renderer output. `TContent` is narrowed by each adapter:
 *   - HTML / Markdown renderers   → `RenderResult<string>`
 *   - React renderer              → `RenderResult<ReactNode>` (renderer-side)
 *   - DOCX element renderer       → `RenderResult<DocxElement>` (renderer-side)
 *
 * The skeleton stays free of React / DOCX type imports so the PBC can be
 * consumed without bringing those toolchains along.
 */
export interface RenderResult<TContent = unknown> {
  content: TContent;
  assets?: RenderAsset[];
  /** Free-form metadata (render duration, warnings, etc.). */
  metadata?: Record<string, unknown>;
}

/**
 * Per-render call context. Passed through `renderBlock` /
 * `renderComposition`; renderers branch on `output` and consume the
 * optional `theme` / `imageEngine` when present.
 *
 * `imageEngine` is typed as `unknown` here so the PBC remains usable
 * without `@axle/pbc-image-engine` being installed; consumers that depend
 * on both packages narrow it via:
 *
 *   import type { ImageEngine } from "@axle/pbc-image-engine";
 *   const ctx: RenderContext = { ..., imageEngine: myEngine satisfies ImageEngine };
 */
export interface RenderContext {
  output: RenderOutput;
  theme?: DesignTokens;
  locale?: Locale;
  /**
   * Optional `@axle/pbc-image-engine` `ImageEngine`. The dependency is a
   * peerDependency so apps without image generation needs are not forced
   * to install the engine. See package.json `peerDependenciesMeta`.
   */
  imageEngine?: unknown;
  /** Free-form metadata forwarded to renderers (page id, A/B variant). */
  metadata?: Record<string, unknown>;
}

/**
 * Block definition. Each of the 23 blocks (added in WI-502) implements
 * this contract. The schema is a zod schema so callers can validate
 * payloads before render and the AI copy pipeline (WI-507) can sample
 * shapes for prompt construction.
 */
export interface BlockDefinition<TData = unknown, TContent = unknown> {
  id: BlockId;
  category: BlockCategory;
  /** Stable human-readable name (English, snake_case-free). */
  name: string;
  description: string;
  /**
   * Variant ids the block supports (e.g. "minimal" / "rich" / "compact").
   * The render function MUST handle the absence of a variant by falling
   * back to the first listed entry.
   */
  variants?: string[];
  schema: ZodSchema<TData>;
  render: (data: TData, context: RenderContext) => RenderResult<TContent>;
}

/**
 * Page composition — the ordered list of block instances that make up a
 * page. Apps persist this shape (DB / JSON file) and pass it to
 * `renderComposition()` to materialize.
 */
export interface PageComposition {
  blocks: Array<{
    id: BlockId;
    data: unknown;
    variant?: string;
  }>;
  /**
   * Theme name resolved by the consumer (e.g. a row id in their
   * design-tokens table). Renderers receive the resolved `DesignTokens`
   * via `RenderContext.theme`, not this field.
   */
  theme?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Validation outcome surfaced by `validateBlockData` (WI-502).
 */
export interface BlockValidationResult {
  ok: boolean;
  /** Human-readable error messages. Populated only when `ok === false`. */
  errors?: string[];
}

/* ------------------------------------------------------------------ */
/* AI copy generation pipeline (WI-507)                                */
/* ------------------------------------------------------------------ */

/**
 * Input to the AI copy pipeline. The pipeline runs in 5 stages
 * (intake → analyze → anchor copy → block copy → assemble) per
 * `ai-pipeline-design.md`; this skeleton fixes only the input/output
 * shapes so the WI-507 implementer can swap pipeline internals without
 * breaking callers.
 */
export interface CopyGenerationRequest {
  /** Free-form user intent in natural language (any language). */
  intent: string;
  industry?: string;
  /** Block ids the caller wants populated. */
  targetBlocks: BlockId[];
  /** Optional brand voice descriptor (e.g. "playful" / "executive"). */
  brandTone?: string;
  language?: Locale;
}

export interface CopyGenerationResult {
  /** Block instances ready to feed into a `PageComposition`. */
  blocks: Array<{ id: BlockId; data: unknown }>;
  /** Why the AI chose this copy — surfaced for human review / audit. */
  rationale: string;
  /** Wall-clock duration in milliseconds. */
  generationTime: number;
}

/* ------------------------------------------------------------------ */
/* Engine surface (forward declaration for dependent PBCs)             */
/* ------------------------------------------------------------------ */

/**
 * Public surface of the block-builder. Implementations of `renderBlock`,
 * `renderComposition`, `generateCopy`, `validateBlockData`, and the
 * `BLOCKS` registry land in WI-502..WI-507. Exposed now so dependent
 * PBCs can declare their dependency against the contract.
 */
export interface BlockBuilderEngine {
  renderBlock(blockId: BlockId, data: unknown, context: RenderContext): RenderResult;
  renderComposition(
    composition: PageComposition,
    context: RenderContext,
  ): Promise<RenderResult[]>;
  generateCopy(request: CopyGenerationRequest): Promise<CopyGenerationResult>;
  validateBlockData(blockId: BlockId, data: unknown): BlockValidationResult;
}
