import {
  AlignmentType,
  convertMillimetersToTwip,
  HeadingLevel,
  IStylesOptions,
  PageOrientation,
  ISectionOptions,
  IPageMarginAttributes,
} from "docx";

/** A4 page size in twips (1/20 of a point) */
export const A4_PAGE_SIZE = {
  width: convertMillimetersToTwip(210),
  height: convertMillimetersToTwip(297),
  orientation: PageOrientation.PORTRAIT,
} as const;

/** Standard Korean business document margins (25mm on all sides) */
export const STANDARD_MARGINS: IPageMarginAttributes = {
  top: convertMillimetersToTwip(25),
  bottom: convertMillimetersToTwip(25),
  left: convertMillimetersToTwip(25),
  right: convertMillimetersToTwip(25),
};

/** Primary Korean font — Malgun Gothic (맑은 고딕) */
export const FONT_KOREAN = "맑은 고딕";
/** Fallback Latin font */
export const FONT_LATIN = "Times New Roman";

/** Base font size in half-points (24 = 12pt) */
export const FONT_SIZE_BODY = 24; // 12pt
export const FONT_SIZE_H1 = 36; // 18pt
export const FONT_SIZE_H2 = 28; // 14pt
export const FONT_SIZE_H3 = 24; // 12pt

/**
 * Paragraph spacing — before/after in twips.
 * 1 point = 20 twips.
 */
export const SPACING = {
  afterParagraph: 160, // 8pt
  afterHeading1: 240, // 12pt
  afterHeading2: 200, // 10pt
  lineRule: "auto" as const,
  line: 276, // 1.15× line spacing
} as const;

/**
 * Returns the document-level styles configuration applied to all documents
 * generated by the precision editor.
 */
export function buildDocxStyles(): IStylesOptions {
  return {
    default: {
      document: {
        run: {
          font: { name: FONT_KOREAN, eastAsia: FONT_KOREAN },
          size: FONT_SIZE_BODY,
        },
        paragraph: {
          spacing: { after: SPACING.afterParagraph, line: SPACING.line },
          alignment: AlignmentType.JUSTIFIED,
        },
      },
      heading1: {
        run: {
          font: { name: FONT_KOREAN, eastAsia: FONT_KOREAN },
          size: FONT_SIZE_H1,
          bold: true,
          color: "1F2937",
        },
        paragraph: {
          spacing: { before: 360, after: SPACING.afterHeading1 },
        },
      },
      heading2: {
        run: {
          font: { name: FONT_KOREAN, eastAsia: FONT_KOREAN },
          size: FONT_SIZE_H2,
          bold: true,
          color: "374151",
        },
        paragraph: {
          spacing: { before: 280, after: SPACING.afterHeading2 },
        },
      },
      heading3: {
        run: {
          font: { name: FONT_KOREAN, eastAsia: FONT_KOREAN },
          size: FONT_SIZE_H3,
          bold: true,
          color: "4B5563",
        },
        paragraph: {
          spacing: { before: 200, after: 160 },
        },
      },
    },
  };
}

/**
 * Returns base section properties (A4, margins) for a docx Section.
 */
export function buildSectionProperties(): ISectionOptions["properties"] {
  return {
    page: {
      size: A4_PAGE_SIZE,
      margin: STANDARD_MARGINS,
      pageNumbers: {
        start: 1,
      },
    },
  };
}

/** Maps a heading level (1-3) to a docx HeadingLevel value */
export function toHeadingLevel(
  level: 1 | 2 | 3
): (typeof HeadingLevel)[keyof typeof HeadingLevel] {
  switch (level) {
    case 1:
      return HeadingLevel.HEADING_1;
    case 2:
      return HeadingLevel.HEADING_2;
    case 3:
      return HeadingLevel.HEADING_3;
  }
}
