/**
 * /api/erp/intake
 *
 *   POST — Upload a receipt image, create an IntakeDraft, run OCR synchronously
 *          and store fuzzy-match suggestions for the review screen.
 *
 *          Flow (mirrors business-card pattern — direct call, no AiJob row):
 *            1. requireErpScope("erp:write")
 *            2. Validate multipart file (image/*, max 10MB)
 *            3. Create IntakeDraft (cuid default, blobUrl placeholder)
 *            4. uploadReceipt → blobUrl
 *            5. parseReceipt(buf, mime) — on failure store errorMsg, no match
 *            6. Fuzzy-match items vs Products and vendor vs Clients
 *               (Decimal fields stringified — Prisma Decimal is not JSON-safe)
 *            7. Update draft with blobUrl + OCR + matches + errorMsg
 *
 *   GET — List IntakeDraft rows for the active tenant. Optional `status`
 *         filter (PENDING | CONFIRMED | DISCARDED). Sorted by createdAt desc,
 *         capped at 50 entries.
 *
 *  Vercel timeout: 60s. Claude Vision can spend 30+s on a single retry and
 *  the route runs the full OCR+match pipeline synchronously; Pro Fluid is
 *  required for the upload route, but other endpoints in this module stay
 *  on the default 10s budget.
 */

import { prisma } from "@axle/db";
import { parseReceipt } from "@axle/ocr";
import {
  requireErpScope,
  toResponse,
  erpBadRequest,
  erpErrorResponse,
  ErpAuthError,
} from "@/lib/erp/auth";
import { uploadReceipt } from "@/lib/erp/blob";
import { topMatches } from "@/lib/erp/fuzzy-match";
import { serializeIntakeDraft } from "@/lib/erp/serialize";

// Claude Vision (parseReceipt) can need 30+s with retries — Pro Fluid 60s.
export const maxDuration = 60;

const ALLOWED_STATUSES = ["PENDING", "CONFIRMED", "DISCARDED"] as const;
type DraftStatusFilter = (typeof ALLOWED_STATUSES)[number];

const MAX_UPLOAD_BYTES = 10 * 1024 * 1024;

interface ParsedReceiptItem {
  name?: unknown;
  qty?: unknown;
  unitPrice?: unknown;
  unit?: unknown;
}

export async function POST(req: Request): Promise<Response> {
  try {
    const ctx = await requireErpScope("erp:write");

    let formData: FormData;
    try {
      formData = await req.formData();
    } catch {
      return erpBadRequest("multipart/form-data required");
    }

    const file = formData.get("file");
    if (!(file instanceof File)) {
      return erpBadRequest("file required");
    }
    if (!file.type || !file.type.startsWith("image/")) {
      return erpBadRequest("image only");
    }
    if (file.size > MAX_UPLOAD_BYTES) {
      return erpErrorResponse(413, "PAYLOAD_TOO_LARGE", "max 10MB");
    }

    const buf = Buffer.from(await file.arrayBuffer());

    // 1. Create the draft first so we can scope the blob path by draftId.
    //    cuid is generated by Prisma — we never pass an explicit id.
    let draft = await prisma.intakeDraft.create({
      data: {
        orgId: ctx.orgId,
        userId: ctx.userId,
        blobUrl: "",
        ocrJson: {},
        parsedJson: {},
        matchSuggestions: {},
        status: "PENDING",
      },
    });

    // 2. Upload to Vercel Blob (path uses draft.id so cleanup can correlate).
    const blobUrl = await uploadReceipt(
      ctx.orgId,
      draft.id,
      buf,
      file.type,
    );

    // 3. Synchronous OCR (business-card pattern). Failures are non-fatal —
    //    the draft persists with an errorMsg so the user can retry later.
    let ocrJson: unknown = {};
    let parsedJson: unknown = {};
    let errorMsg: string | null = null;
    let parsedItems: ParsedReceiptItem[] = [];
    let parsedVendor = "";
    try {
      const ocr = await parseReceipt(buf, file.type);
      ocrJson = ocr;
      parsedJson = ocr;
      parsedItems = Array.isArray(ocr.items)
        ? (ocr.items as ParsedReceiptItem[])
        : [];
      parsedVendor = typeof ocr.vendor === "string" ? ocr.vendor : "";
    } catch (err) {
      errorMsg = err instanceof Error ? err.message : String(err);
    }

    // 4. Fuzzy-match suggestions. Skipped if OCR failed.
    let matchSuggestions: unknown = {};
    if (!errorMsg) {
      const [products, clients] = await Promise.all([
        prisma.product.findMany({
          where: { orgId: ctx.orgId, archived: false },
          take: 500,
        }),
        prisma.client.findMany({
          where: { orgId: ctx.orgId },
          take: 200,
          select: { id: true, name: true },
        }),
      ]);

      // Decimal → string before storing as JSON. Prisma Decimal is not
      // JSON-serializable; passing it directly produces "[object]" / loses
      // precision when read back.
      const productLite = products.map((p) => ({
        id: p.id,
        name: p.name,
        sku: p.sku,
        unit: p.unit,
        unitPrice: p.unitPrice.toString(),
      }));
      const clientLite = clients.map((c) => ({ id: c.id, name: c.name }));

      matchSuggestions = {
        items: parsedItems.map((it) => {
          const name = typeof it?.name === "string" ? it.name : "";
          return {
            query: name,
            candidates: topMatches(name, productLite, (p) => p.name),
          };
        }),
        counterparty: {
          query: parsedVendor,
          candidates: topMatches(parsedVendor, clientLite, (c) => c.name),
        },
      };
    }

    // 5. Persist the enriched draft.
    draft = await prisma.intakeDraft.update({
      where: { id: draft.id },
      data: {
        blobUrl,
        ocrJson: ocrJson as never,
        parsedJson: parsedJson as never,
        matchSuggestions: matchSuggestions as never,
        errorMsg,
      },
    });

    return Response.json(
      { draftId: draft.id, draft: serializeIntakeDraft(draft) },
      { status: 201 },
    );
  } catch (err) {
    if (err instanceof ErpAuthError) return toResponse(err);
    return toResponse(err);
  }
}

export async function GET(req: Request): Promise<Response> {
  try {
    const ctx = await requireErpScope("erp:read");
    const url = new URL(req.url);
    const rawStatus = url.searchParams.get("status");
    const status =
      rawStatus && (ALLOWED_STATUSES as readonly string[]).includes(rawStatus)
        ? (rawStatus as DraftStatusFilter)
        : undefined;

    const drafts = await prisma.intakeDraft.findMany({
      where: { orgId: ctx.orgId, ...(status ? { status } : {}) },
      orderBy: { createdAt: "desc" },
      take: 50,
    });

    return Response.json({ items: drafts.map(serializeIntakeDraft) });
  } catch (err) {
    return toResponse(err);
  }
}
